PyTorch

In [3]:
print("hello i am begining PyTorch!")

hello i am begining PyTorch!


# LIBRARIES TO IMPORT IN PYTHON FOR PyTorch

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cpu


*Intoduction to Tensor

# Scalar

In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

# Vector

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [10]:
vector.ndim

1

# MATRIX

In [11]:
MATRIX = torch.tensor([[2,4],[5,6]])
MATRIX

tensor([[2, 4],
        [5, 6]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

# TENSOR

In [14]:
TENSOR =torch.tensor([[[2,3,4],[9,7,6],[11,72,8]]])
TENSOR

tensor([[[ 2,  3,  4],
         [ 9,  7,  6],
         [11, 72,  8]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR.dtype #USED FOR DEFAULT DATATYPE

torch.int64

### RANDOM TENSOR

In [18]:
random_tensor =torch.rand(1,3,5)
random_tensor

tensor([[[0.4343, 0.2212, 0.0199, 0.9634, 0.4452],
         [0.6375, 0.1629, 0.1583, 0.0459, 0.4995],
         [0.0283, 0.2375, 0.2402, 0.1655, 0.3112]]])

## Tensor of all zeros

In [19]:
tensor_of_all_zeros = torch.zeros(3,4)
tensor_of_all_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#Tensor of all zeros

In [20]:
tensor_of_all_ones = torch.ones(4,5)
tensor_of_all_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

# Creating the range of TENSOR & TENSOR-LIKE

In [21]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
one_to_ten = torch.arange( start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#TENSOR-LIKE

In [23]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatype 

**Note:**  Errors which can we get while working on the tensors are:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device 

In [24]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,4.0,6.0],
                             dtype=None,#datatype of teh tensor(float 32 or float 16)
                             device=None,#device in which u are
                             requires_grad=False)#weather to track the gradiants with tensor operation
float_32_tensor

tensor([3., 4., 6.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
#changing the datatype of the tensor
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [27]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 36.])

In [28]:
int_32_tensor = torch.tensor([3,4,5],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [29]:
#int * float
int_32_tensor*float_32_tensor

tensor([ 9., 16., 30.])

### Getting the info from the tensor(tensor attributes)
1. Tensors not right datatype - torch.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on right device - tensor.device

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3755, 0.9179, 0.8929, 0.8424],
        [0.7776, 0.8896, 0.1649, 0.8524],
        [0.0508, 0.4880, 0.8990, 0.6290]])

In [31]:
# Testing the attributes
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Devcie of tensor : {some_tensor.device}")

tensor([[0.3755, 0.9179, 0.8929, 0.8424],
        [0.7776, 0.8896, 0.1649, 0.8524],
        [0.0508, 0.4880, 0.8990, 0.6290]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Devcie of tensor : cpu


# Manipulation of the Tensors (tensor operation)

1. Addition
2. Substraction 
3. Multiplication
4. Division
5. Matrix Multiplication

In [32]:
#adding 100 to a tensor
tensor = torch .tensor([4,5,6])
tensor + 100

tensor([104, 105, 106])

In [33]:
#substraction
tensor - 10

tensor([-6, -5, -4])

In [34]:
#multiplying tensor to 10
tensor *10

tensor([40, 50, 60])

In [35]:
#Division
tensor / 10

tensor([0.4000, 0.5000, 0.6000])

## Matrix multiplication

1. element wise
2. dot product

In [36]:
# Element wise

tensor * tensor

tensor([16, 25, 36])

In [37]:
# Matrix multiplication (torch.matmul)
torch.matmul(tensor,tensor)

tensor(77)

In [38]:
tensor

tensor([4, 5, 6])

## There are two main rules that performing matrix mutliplication needs to satisfy

* The inner dimensions must match:
1. (1, 2) @ (3, 2) won't work
2. (2, 3) @ (3, 2) will work
3. (3, 2) @ (2, 3) will work

* The resulting matrix has the shape of the ** outer dimensions **:
1. (2, 3) @ (3, 2) -> (2, 2)
2. (3, 2) @ (2, 3) -> (3, 3)

In [39]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.5735, 0.5665, 0.6207],
        [0.1589, 0.1373, 0.1608],
        [0.3190, 0.2715, 0.3206]])

In [40]:
tensor @ tensor

tensor(77)

# " @ " , " torch.mm " , " torch.matmul " are the same thing 

# Matrix Transpose:
switches the axes or dimensions

In [41]:
tensor_a = torch.rand(3,2)
tensor_a

tensor([[0.6089, 0.2337],
        [0.3093, 0.4994],
        [0.2228, 0.5617]])

In [42]:
tensor_b = torch.rand(3,2)
tensor_b

tensor([[0.7601, 0.0018],
        [0.3885, 0.4823],
        [0.0044, 0.9774]])

In [43]:
# using transpose function for multiplication of same size of matrix
tensor_b.T.shape
tensor_a @ tensor_b.T

tensor([[0.4632, 0.3493, 0.2311],
        [0.2360, 0.3611, 0.4895],
        [0.1703, 0.3575, 0.5500]])

In [44]:
# shape after the transpose

tensor_b.shape,tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

# Finding the min , max , mean , sum etc. of the tensor


In [45]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
#find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [47]:
#find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [48]:
#find the meam
# torch.mean(x) , x.mean() [shape error]
#torch.mean() require a float datatype

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [49]:
#find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [50]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
# argmin() -> tells the index of min value
x.argmin()

tensor(0)

In [52]:
# argmax() -> tells the index of max value
x.argmax()

tensor(9)

In [53]:
x[9]

tensor(90)

## Reshaping , view , stacking , squeezing and unsqueezing the tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [54]:
# create  a tensor

x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [57]:
# change the view
z= x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
# change in the element in z means changing the element of x as the view TENSOR shares the same memory
z[:,0] = 11
z,x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [59]:
# stacking of tensor

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [60]:
x_stacked = torch.stack([x,x,x,x],dim =1)
x_stacked

tensor([[11., 11., 11., 11.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [61]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [62]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked , x_stacked.shape

(tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,
          2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([36]))

In [63]:
#squeezing a tensor(removes all single dimensions frm the tensor)
x.squeeze()

tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [64]:
x.squeeze().shape

torch.Size([9])

In [65]:
#unsqueezing a tensor(add single dimensions to the tensor)
x.unsqueeze(dim = 0)

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [66]:
x.unsqueeze(dim = 1)

tensor([[11.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]])

In [67]:
#torch.permute : rearranges the dimensions of a target tensor in a specified order
x_orginal = torch.rand(size =(224 , 224 ,3)) # height , width , colour channels
#x_orginal

In [68]:
#permute the original tensor to rearrange the the axis (or dim) order
x_permuted = x_orginal.permute(2,0,1) # shifting 2->0 , 0->1 , 1->2
#x_permuted

In [69]:
print(f"original shape : {x_orginal.shape}")
print(f"permuted shape : {x_permuted.shape}")

original shape : torch.Size([224, 224, 3])
permuted shape : torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is simailar to indexing with NumPy.


In [70]:
#creating a tensor
x= torch.arange(1,10).reshape(3,3,1)

x

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [71]:
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [72]:
# Let's index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
x[0][0]

tensor([1, 2, 3])

In [74]:
x[0][0][0]

tensor(1)

In [75]:
# we can use " : " to select " all " of the target
x[:,0]

tensor([[1, 2, 3]])

In [76]:
x[:,1,:]

tensor([[4, 5, 6]])

In [77]:
x[:,:,2]

tensor([[3, 6, 9]])

In [78]:
# index to return 9
x[:,2,2]

tensor([9])

In [79]:
# index to return 3 , 6 , 9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy
NumPy is famous Python library.

This is because PyTorch ahs functionality to intract with it.

* Data in NumPy-> PyTorch tensor : torch.from_numpy(ndarray)
* PyTorch tensor-> NumPy : torch.Tensor.numpy()

In [80]:
# NumPy array -> tensor
import torch
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)

array , tensor
#tensor reflects default dtype of numpy when coverted from numpy to tensor unless specified

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [81]:
array.dtype

dtype('float64')

In [82]:
tensor.dtype

torch.float64

In [83]:
# Tensor -> NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

#numpy array reflects default dtype of tensor when coverted from tensor to numpy array unless specified

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
numpy_tensor.dtype

dtype('float32')

tensor  and numpy array do not share the same memory

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them
of the data -> again -> again -> again ...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [85]:
# Create 2 random tensors
a=torch.rand(4,5)
b=torch.rand(4,5)

print(a)
print(b)
print (a == b)



tensor([[0.9076, 0.0339, 0.2277, 0.4890, 0.6685],
        [0.6857, 0.2273, 0.3980, 0.3869, 0.4883],
        [0.0600, 0.3145, 0.1606, 0.4120, 0.6187],
        [0.9150, 0.5492, 0.4359, 0.6984, 0.0789]])
tensor([[0.2858, 0.9783, 0.7923, 0.2222, 0.1547],
        [0.1465, 0.7712, 0.2754, 0.8461, 0.1077],
        [0.6967, 0.3010, 0.6294, 0.8133, 0.3799],
        [0.8803, 0.1197, 0.2329, 0.1992, 0.3914]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [86]:
# Let's make random but reproducible tensors

In [87]:
## set a reandom seed
random_seed = 100

torch.manual_seed(random_seed)
c= torch.rand(3,4)

torch.manual_seed(random_seed)
d= torch.rand(3,4)

print(c)
print(d)
print (c == d)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# GPUs usage in PyTorch

In [99]:
!nvidia-smi # No GPU available

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [88]:
import torch
torch.cuda.is_available()

False

In [89]:
# Set up the device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [90]:
#count the no. of devices
torch.cuda.device_count()

0

## Putting tensors (or Model ) on GPU

In [91]:
#create a tensor (default on cpu)
tensor = torch.tensor([1,2,3])

#Tensor not on GPU
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
# Move tensor to the GPU if available
tensor_gpu = tensor.to(device)
tensor_gpu , tensor_gpu.device  # i don't have a GPU(cuda)

(tensor([1, 2, 3]), device(type='cpu'))

### Moving tensors back to the CPU

In [ ]:
# if tensor is in GPU , can't transform it to NumPy
tensor_gpu.numpy() # i don't have a GPU other wise it throws error

array([1, 2, 3])

In [96]:
# GPU -> CPU tensor
tensor_cpu = tensor_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])

In [100]:
print(" PyTorch Basics Completed!")

 PyTorch Basics Completed!
