PyTorch

In [9]:
print("hello i am begining PyTorch!")

hello i am begining PyTorch!


#LIBRARIES TO IMPORT IN PYTHON FOR PyTorch

In [10]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cpu


*Intoduction to Tensor

#Scalar

In [11]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [13]:
scalar.item()

7

#Vector

In [14]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.shape

torch.Size([2])

In [16]:
vector.ndim

1

#MATRIX

In [17]:
MATRIX = torch.tensor([[2,4],[5,6]])
MATRIX

tensor([[2, 4],
        [5, 6]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([2, 2])

#TENSOR

In [20]:
TENSOR =torch.tensor([[[2,3,4],[9,7,6],[11,72,8]]])
TENSOR

tensor([[[ 2,  3,  4],
         [ 9,  7,  6],
         [11, 72,  8]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR.dtype #USED FOR DEFAULT DATATYPE

torch.int64

#RANDOM TENSOR

In [24]:
random_tensor =torch.rand(1,3,5)
random_tensor

tensor([[[0.4173, 0.3388, 0.9196, 0.2702, 0.7420],
         [0.7375, 0.1336, 0.1870, 0.8761, 0.2755],
         [0.2398, 0.5247, 0.3090, 0.0355, 0.4786]]])

#Tensor of all zeros

In [25]:
tensor_of_all_zeros = torch.zeros(3,4)
tensor_of_all_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#Tensor of all zeros

In [26]:
tensor_of_all_ones = torch.ones(4,5)
tensor_of_all_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

#Creating the range of TENSOR & TENSOR-LIKE

In [27]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
one_to_ten = torch.arange( start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#TENSOR-LIKE

In [29]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype 

**Note:**  Errors which can we get while working on the tensors are:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device 

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,4.0,6.0],
                             dtype=None,#datatype of teh tensor(float 32 or float 16)
                             device=None,#device in which u are
                             requires_grad=False)#weather to track the gradiants with tensor operation
float_32_tensor

tensor([3., 4., 6.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
#changing the datatype of the tensor
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [36]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 36.])

In [38]:
int_32_tensor = torch.tensor([3,4,5],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [39]:
#int * float
int_32_tensor*float_32_tensor

tensor([ 9., 16., 30.])

### Getting the info from the tensor(tensor attributes)
1. Tensors not right datatype - torch.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on right device - tensor.device

In [40]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8385, 0.1584, 0.4937, 0.5586],
        [0.9983, 0.2441, 0.1321, 0.4336],
        [0.1984, 0.5965, 0.3976, 0.8594]])

In [43]:
# Testing the attributes
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Devcie of tensor : {some_tensor.device}")

tensor([[0.8385, 0.1584, 0.4937, 0.5586],
        [0.9983, 0.2441, 0.1321, 0.4336],
        [0.1984, 0.5965, 0.3976, 0.8594]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Devcie of tensor : cpu


### Manipulation of the Tensors (tensor operation)

1. Addition
2. Substraction 
3. Multiplication
4. Division
5. Matrix Multiplication

In [ ]:
#adding 100 to a tensor
tensor = torch .tensor([4,5,6])
tensor + 100

tensor([104, 105, 106])

In [47]:
#substraction
tensor - 10

tensor([-6, -5, -4])

In [45]:
#multiplying tensor to 10
tensor *10

tensor([40, 50, 60])

In [ ]:
#Division
tensor / 10

tensor([0.4000, 0.5000, 0.6000])

### Matrix multiplication

1. element wise
2. dot product

In [49]:
# Element wise

tensor * tensor

tensor([16, 25, 36])

In [51]:
# Matrix multiplication (torch.matmul)
torch.matmul(tensor,tensor)

tensor(77)

In [52]:
tensor

tensor([4, 5, 6])

There are two main rules that performing matrix mutliplication needs to satisfy

* The inner dimensions must match:
1. (1, 2) @ (3, 2) won't work
2. (2, 3) @ (3, 2) will work
3. (3, 2) @ (2, 3) will work

* The resulting matrix has the shape of the ** outer dimensions **:
1. (2, 3) @ (3, 2) -> (2, 2)
2. (3, 2) @ (2, 3) -> (3, 3)

In [53]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.9782, 1.1389, 0.6168],
        [0.9960, 1.2057, 0.6387],
        [0.7739, 1.0199, 0.5154]])

In [54]:
tensor @ tensor

tensor(77)

" @ " , " torch.mm " , " torch.matmul " are the same thing 

### Matrix Transpose:
switches the axes or dimensions

In [56]:
tensor_a = torch.rand(3,2)
tensor_a

tensor([[0.3561, 0.2761],
        [0.8144, 0.5418],
        [0.7751, 0.7702]])

In [57]:
tensor_b = torch.rand(3,2)
tensor_b

tensor([[0.5379, 0.3612],
        [0.3098, 0.4945],
        [0.1070, 0.9049]])

In [61]:
# using transpose function for multiplication of same size of matrix
tensor_b.T.shape
tensor_a @ tensor_b.T

tensor([[0.2913, 0.2469, 0.2879],
        [0.6337, 0.5202, 0.5774],
        [0.6951, 0.6210, 0.7799]])

In [64]:
# shape after the transpose

tensor_b.shape,tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

# Finding the min , max , mean , sum etc. of the tensor


In [69]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [71]:
#find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [ ]:
#find the meam
# torch.mean(x) , x.mean() [shape error]
#torch.mean() require a float datatype

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [78]:
#find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### finding the positional min and max

In [79]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
# argmin() -> tells the index of min value
x.argmin()

tensor(0)

In [82]:
# argmax() -> tells the index of max value
x.argmax()

tensor(9)

In [86]:
x[9]

tensor(90)

## Reshaping , view , stacking , squeezing and unsqueezing the tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [93]:
# create  a tensor

x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [94]:
# add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [95]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [102]:
# change the view
z= x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# change in the element in z means changing the element of x as the view TENSOR shares the same memory
z[:,0] = 11
z,x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [107]:
# stacking of tensor

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [108]:
x_stacked = torch.stack([x,x,x,x],dim =1)
x_stacked

tensor([[11., 11., 11., 11.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [109]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [ ]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked , x_stacked.shape

(tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,
          2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([36]))