PyTorch

In [1]:
print("hello i am begining PyTorch!")

hello i am begining PyTorch!


#LIBRARIES TO IMPORT IN PYTHON FOR PyTorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cpu


*Intoduction to Tensor

#Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

#Vector

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector.ndim

1

#MATRIX

In [9]:
MATRIX = torch.tensor([[2,4],[5,6]])
MATRIX

tensor([[2, 4],
        [5, 6]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

#TENSOR

In [12]:
TENSOR =torch.tensor([[[2,3,4],[9,7,6],[11,72,8]]])
TENSOR

tensor([[[ 2,  3,  4],
         [ 9,  7,  6],
         [11, 72,  8]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR.dtype #USED FOR DEFAULT DATATYPE

torch.int64

#RANDOM TENSOR

In [16]:
random_tensor =torch.rand(1,3,5)
random_tensor

tensor([[[0.1381, 0.5313, 0.8221, 0.6320, 0.2583],
         [0.9696, 0.1275, 0.0593, 0.3196, 0.3465],
         [0.1794, 0.7525, 0.3755, 0.2246, 0.9078]]])

#Tensor of all zeros

In [17]:
tensor_of_all_zeros = torch.zeros(3,4)
tensor_of_all_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#Tensor of all zeros

In [18]:
tensor_of_all_ones = torch.ones(4,5)
tensor_of_all_ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

#Creating the range of TENSOR & TENSOR-LIKE

In [19]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
one_to_ten = torch.arange( start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#TENSOR-LIKE

In [21]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatype 

**Note:**  Errors which can we get while working on the tensors are:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device 

In [22]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.0,4.0,6.0],
                             dtype=None,#datatype of teh tensor(float 32 or float 16)
                             device=None,#device in which u are
                             requires_grad=False)#weather to track the gradiants with tensor operation
float_32_tensor

tensor([3., 4., 6.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
#changing the datatype of the tensor
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 6.], dtype=torch.float16)

In [25]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 36.])

In [26]:
int_32_tensor = torch.tensor([3,4,5],dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [27]:
#int * float
int_32_tensor*float_32_tensor

tensor([ 9., 16., 30.])

### Getting the info from the tensor(tensor attributes)
1. Tensors not right datatype - torch.dtype
2. Tensors not right shape - tensor.shape
3. Tensors not on right device - tensor.device

In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0505, 0.6095, 0.2370, 0.6172],
        [0.5176, 0.7881, 0.2908, 0.5113],
        [0.1743, 0.4116, 0.4355, 0.6680]])

In [29]:
# Testing the attributes
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Devcie of tensor : {some_tensor.device}")

tensor([[0.0505, 0.6095, 0.2370, 0.6172],
        [0.5176, 0.7881, 0.2908, 0.5113],
        [0.1743, 0.4116, 0.4355, 0.6680]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Devcie of tensor : cpu


### Manipulation of the Tensors (tensor operation)

1. Addition
2. Substraction 
3. Multiplication
4. Division
5. Matrix Multiplication

In [30]:
#adding 100 to a tensor
tensor = torch .tensor([4,5,6])
tensor + 100

tensor([104, 105, 106])

In [31]:
#substraction
tensor - 10

tensor([-6, -5, -4])

In [32]:
#multiplying tensor to 10
tensor *10

tensor([40, 50, 60])

In [33]:
#Division
tensor / 10

tensor([0.4000, 0.5000, 0.6000])

### Matrix multiplication

1. element wise
2. dot product

In [34]:
# Element wise

tensor * tensor

tensor([16, 25, 36])

In [35]:
# Matrix multiplication (torch.matmul)
torch.matmul(tensor,tensor)

tensor(77)

In [36]:
tensor

tensor([4, 5, 6])

There are two main rules that performing matrix mutliplication needs to satisfy

* The inner dimensions must match:
1. (1, 2) @ (3, 2) won't work
2. (2, 3) @ (3, 2) will work
3. (3, 2) @ (2, 3) will work

* The resulting matrix has the shape of the ** outer dimensions **:
1. (2, 3) @ (3, 2) -> (2, 2)
2. (3, 2) @ (2, 3) -> (3, 3)

In [37]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.0980, 0.2191, 0.0845],
        [0.4208, 0.7665, 0.3335],
        [0.5891, 0.9066, 0.4387]])

In [38]:
tensor @ tensor

tensor(77)

" @ " , " torch.mm " , " torch.matmul " are the same thing 

### Matrix Transpose:
switches the axes or dimensions

In [39]:
tensor_a = torch.rand(3,2)
tensor_a

tensor([[0.2028, 0.4645],
        [0.1582, 0.0761],
        [0.3710, 0.5852]])

In [40]:
tensor_b = torch.rand(3,2)
tensor_b

tensor([[0.4107, 0.7403],
        [0.8598, 0.7605],
        [0.6761, 0.5081]])

In [41]:
# using transpose function for multiplication of same size of matrix
tensor_b.T.shape
tensor_a @ tensor_b.T

tensor([[0.4272, 0.5276, 0.3731],
        [0.1213, 0.1938, 0.1456],
        [0.5856, 0.7641, 0.5482]])

In [42]:
# shape after the transpose

tensor_b.shape,tensor_b.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

# Finding the min , max , mean , sum etc. of the tensor


In [43]:
# create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
#find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [45]:
#find the max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [46]:
#find the meam
# torch.mean(x) , x.mean() [shape error]
#torch.mean() require a float datatype

torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [47]:
#find the sum
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

### finding the positional min and max

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# argmin() -> tells the index of min value
x.argmin()

tensor(0)

In [50]:
# argmax() -> tells the index of max value
x.argmax()

tensor(9)

In [51]:
x[9]

tensor(90)

## Reshaping , view , stacking , squeezing and unsqueezing the tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [52]:
# create  a tensor

x = torch.arange(1. , 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# add an extra dimensions
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [55]:
# change the view
z= x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
# change in the element in z means changing the element of x as the view TENSOR shares the same memory
z[:,0] = 11
z,x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [57]:
# stacking of tensor

x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [58]:
x_stacked = torch.stack([x,x,x,x],dim =1)
x_stacked

tensor([[11., 11., 11., 11.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [59]:
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [60]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked , x_stacked.shape

(tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,
          6.,  7.,  8.,  9., 11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11.,
          2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]),
 torch.Size([36]))

In [ ]:
#squeezing a tensor(removes all single dimensions frm the tensor)
x.squeeze()

tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [70]:
x.squeeze().shape

torch.Size([9])

In [73]:
#unsqueezing a tensor(add single dimensions to the tensor)
x.unsqueeze(dim = 0)

tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [78]:
x.unsqueeze(dim = 1)

tensor([[11.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.]])

In [86]:
#torch.permute : rearranges the dimensions of a target tensor in a specified order
x_orginal = torch.rand(size =(224 , 224 ,3)) # height , width , colour channels
#x_orginal

In [85]:
#permute the original tensor to rearrange the the axis (or dim) order
x_permuted = x_orginal.permute(2,0,1) # shifting 2->0 , 0->1 , 1->2
#x_permuted

In [84]:
print(f"original shape : {x_orginal.shape}")
print(f"permuted shape : {x_permuted.shape}")

original shape : torch.Size([224, 224, 3])
permuted shape : torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is simailar to indexing with NumPy.


In [101]:
#creating a tensor
x= torch.arange(1,10).reshape(3,3,1)

x

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [102]:
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [103]:
# Let's index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [104]:
x[0][0]

tensor([1, 2, 3])

In [105]:
x[0][0][0]

tensor(1)

In [106]:
# we can use " : " to select " all " of the target
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,1,:]

tensor([[4, 5, 6]])

In [117]:
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
# index to return 9
x[:,2,2]

tensor([9])

In [119]:
# index to return 3 , 6 , 9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy
NumPy is famous Python library.

This is because PyTorch ahs functionality to intract with it.

* Data in NumPy-> PyTorch tensor : torch.from_numpy(ndarray)
* PyTorch tensor-> NumPy : torch.Tensor.numpy()

In [127]:
# NumPy array -> tensor
import torch
import numpy as np

array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)

array , tensor
#tensor reflects default dtype of numpy when coverted from numpy to tensor unless specified

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [125]:
array.dtype

dtype('float64')

In [126]:
tensor.dtype

torch.float64

In [ ]:
# Tensor -> NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

#numpy array reflects default dtype of tensor when coverted from tensor to numpy array unless specified

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [131]:
numpy_tensor.dtype

dtype('float32')

tensor  and numpy array do not share the same memory

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them
of the data -> again -> again -> again ...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.


In [132]:
# Create 2 random tensors
a=torch.rand(4,5)
b=torch.rand(4,5)

print(a)
print(b)
print (a == b)



tensor([[0.5854, 0.6795, 0.4034, 0.0873, 0.9204],
        [0.6302, 0.0807, 0.7444, 0.2872, 0.3142],
        [0.0139, 0.3296, 0.2233, 0.7709, 0.7733],
        [0.7011, 0.7517, 0.8784, 0.7215, 0.7162]])
tensor([[0.4267, 0.5219, 0.7518, 0.5617, 0.0197],
        [0.0297, 0.6485, 0.7694, 0.5844, 0.2127],
        [0.8541, 0.7691, 0.7622, 0.1239, 0.7304],
        [0.4913, 0.6388, 0.3886, 0.0021, 0.7736]])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [133]:
# Let's make random but reproducible tensors

In [136]:
## set a reandom seed
random_seed = 100

torch.manual_seed(random_seed)
c= torch.rand(3,4)

torch.manual_seed(random_seed)
d= torch.rand(3,4)

print(c)
print(d)
print (c == d)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
